Update Understanding "focus visible" (SC 2.4.7)
w3c/wcag pull request #1022
Opened 2020-01-27 04:02 UTC by JAWS-test2

Fixes #1001

2025-06-27 13:04 UTC, patrickhlauke commented
Reformatted the additions into the note to account for the changed structure since this PR was first filed, to clear the merge conflict

2025-07-11 16:20 UTC, gundulaniemann commented on understanding/20/focus-visible.html
> +        <p>If there is only one keyboard focusable control on the screen, the success criterion would be met because the visual design presents only one keyboard focusable item. The success criterion
How is the user supposed to work when the focus is not shown initially? How does a screen reader user perceive what happened to the focus?
If the focus is not visible initially, the user doesn't see where the focus is and might initiate an action that is not wanted. Also, having to interact to see the focus reduces efficiency considerable and distracts from the task all the time.

2025-07-21 20:17 UTC, mbgower commented on understanding/20/focus-visible.html
> +        <p>If there is only one keyboard focusable control on the screen, the success criterion would be met because the visual design presents only one keyboard focusable item. The success criterion
I don't think I agree with this: "The success criterion does not require the focus to be visible intially" (and btw, there's a typo in "initially").

There is a difference between a page that does not have an element in focus initially, and one where there is a focusable element that is not properly shown as active. I'm not sure that the number of focusable controls on the screen is relevant to that. 

I do not think this PR sufficiently captures or addresses the initial question in #1001. 

I think these are good questions to provide guidance on:
- can an inoperable element on a page take focus?
- if so, should it have a focus indicator?
- if so, _must_ it have a focus indicator to meet Focus Visible (and not doing so is a failure of 2.4.7?
- conversely, is there a time when inoperable elements receiving focus constitutes a failure of WCAG?

2025-07-25 00:19 UTC, patrickhlauke requested changes
I don't believe this fully answers/closes #1001 

A more thorough answer may be https://github.com/w3c/wcag/pull/1643

2026-06-10 22:59 UTC, closed without merging