David macdonald patch drag pointer
w3c/wcag pull request #1636
Opened 2021-02-10 19:42 UTC by DavidMacDonald

This patch addresses Issue #1225 and disambiguates dragging and path based gestures

2021-02-11 10:12 UTC, detlevhfischer commented on understanding/21/pointer-gestures.html
> +      <p>Dragging is a motion between the start and end points without an intermediate point which can go in any direction and is entirely non-prescriptive, and therefore not path-based.  Although a
For consistency#s sake we should either use "dragging motion" or "dragging movement" in both 2.5.1 and 2.5.7. I leave it to native speakers to determine the better choice.
I believe this text could ans should be shorter (maybe not quire as short as the one it replaces). I can try to rephrase...

2021-02-11 10:39 UTC, detlevhfischer requested changes
See my PR #1638 for what I believe is a more understandable explanation of the difference between path-based gestures and dragging.

2021-02-11 10:39 UTC, detlevhfischer commented on understanding/21/pointer-gestures.html
> +      <h3>Disambiguation of Pointer Gestures and Dragging</h3>
A simpler heading (think COGA) would be "The difference between pointer gestures and dragging"

2021-02-11 10:39 UTC, detlevhfischer commented on understanding/22/dragging-movements.html
> +      <p>In contrast to dragging movements, path-based gestures involve at least an initial directionality of the pointer movement. This is defined by stating that the path has to go through at least
In my view, the sentences added: "The intermediate point defines the gesture as requiring a specific path, even if the complete path is not defined. So, although a user could drag in the same way as a gesture, the difference is that a gesture requires an intermediate point, dragging does not" make the text more verbose without providing more clarity. I would leave the text as it is.

2021-02-16 17:53 UTC, merged

2021-02-16 17:53 UTC, alastc commented
Agreed in the meeting, although further updates are likely.