Alternative rewording of the normative text for 1.4.2 Audio control
w3c/wcag pull request #1825
Opened 2021-05-21 23:12 UTC by patrickhlauke

In contrast to https://github.com/w3c/wcag/pull/1824 this rewording accepts that the mechanism does not necessarily have to be implemented by the web page itself, but - per the definition of mechanism - can also be provided by the user agent/system. What this change does implement though is the clarification for the pause/stop clause that the pausing/stopping must be *independent* from any other audio output (which does address @jake-abma's original concern that a system wide general mute/audio off would automatically satisfy the SC, which is not the intended outcome https://github.com/w3c/wcag/issues/1533

This still changes the structure of the SC text, as suggested by @bruce-usab, to a more understandable list format.

If the change in structure is deemed too radical, the addition of "independenlty from any other audio output" could likely be slotted into the current wording/structure of the SC. while a normative change, I don't believe this actually changes the meaning as intended at the time.

Closes https://github.com/w3c/wcag/issues/1533

2021-05-26 23:26 UTC, patrickhlauke commented
Changed this to be less radical, but still cover the clarification for @jake-abma's concern in #1533, while also incorporating the note along the lines of trusted tester as pointed out by @mraccess77 https://github.com/w3c/wcag/pull/1824#issuecomment-847070698

2022-04-18 10:56 UTC, patrickhlauke commented
Any news on this @alastc ?

2022-04-20 15:26 UTC, bruce-usab requested changes
I am glad to see this PR.  As I noted in the related issue thread, please add short handles to the choices.  This is consistent with other SC using the "one of the following" pattern.  2.1.4, 2.2.1, 2.5.2, 3.3.4, 3.3.6.

2022-04-20 17:08 UTC, patrickhlauke commented
> please add short handles to the choices

ah sorry, meant to do it and then promptly forgot when I made the update to the PR. done now.

2022-08-09 15:46 UTC, awkawk commented
@patrickhlauke If this hasn't been approved as an errata it should have "Erratum Raised" as the label and only gets the "Errata" label once finalized.

2022-08-09 15:48 UTC, patrickhlauke commented
@awkawk i'll leave the tagging up to you and your process ;)

2022-08-11 15:48 UTC, awkawk commented
I think this is a more substantial normative change and will need more time to evaluate implications.

2022-08-12 18:49 UTC, bruce-usab approved these changes
I think the first bullet should end <q>; or</q> rather than a period.

Unfortunately, 2.0/2.1 is not 100% consistent with its <q>at least one of the following is true</q> pattern.

2022-08-16 16:05 UTC, bruce-usab requested changes
The <q>any other audio output of the user agent and</q> is too much of a change for my tastes.

2022-08-16 16:07 UTC, patrickhlauke commented
> The addition of any other audio output of the user agent and is too much of a change for my tastes.

without that, i could claim that going into windows' volume mixer and just muting/changing the volume for Chrome satisfies this, as it's independent of the OS overall

2022-08-16 20:06 UTC, bruce-usab commented
> without that, i could claim that going into windows' volume mixer...

That is beyond the UA, as is asserting PC mute is an option for audio pause/stop.  (Something which, until today, I never would have thought anyone brazen enough to claim.)

The audio (which plays automatically) is on the web page, it obviously follows that the mechanism for controlling the audio must be on the web page.

But we have a few SC which authors can claim to meet by relying upon browser features.  So it is not as tidy as I would like.

Asserting use of platform/hardware to meet web page SC is not a loophole just for this SC.  I do not agree that the idea warrants any air at all.  But if it does, maybe the Conformance Requires need a tweeking?

2022-08-16 20:11 UTC, patrickhlauke commented
> I do not agree that the idea warrants any air at all

well, you do you. seem like this PR https://github.com/w3c/wcag/pull/2621 is superseding this one anyway

2022-08-16 22:40 UTC, alastc commented
I'm afraid this wasn't seen as a sufficient problem to overcome the friction of an SC update: https://www.w3.org/2022/08/16-ag-minutes.html#t10

I'll close this, but there is an understanding update on the cards.

2022-08-16 22:40 UTC, closed without merging

2022-10-11 08:44 UTC, GreggVan commented
+1 to this

And we should do this uniformly as an editorial fix for both clarity and uniformity.  
Suggest this be added to survey 

Proposal 
That throughout WCAG 2.2 (as an editorial fix):
All lists that are "any of the following" have each choice end with ;  and the last choice end with    ; or    (or   ; OR)
All lists that are "all of the following"  have each choice end with ; and the last choice end with    ; and    (or   ; AND)

(The caps MIGHT be justified since it is a logical AND  or  OR …. )



Gregg Vanderheiden
***@***.***



> On Aug 12, 2022, at 11:49 AM, Bruce Bailey ***@***.***> wrote:
> 
> 
> @bruce-usab approved this pull request.
> 
> I think the first bullet should end ; or rather than a period.
> 
> Unfortunately, 2.0/2.1 is not 100% consistent with its at least one of the following is true pattern.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/w3c/wcag/pull/1825#pullrequestreview-1071601889>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACNGDXSHCX4M4E2PEOOMGSDVY2MC7ANCNFSM45J75IDQ>.
> You are receiving this because you are subscribed to this thread.
>