Focus appearance updates from Wilco
w3c/wcag pull request #2578
Opened 2022-08-09 15:19 UTC by alastc

Some parts of: https://docs.google.com/document/d/1kUjK65oIWBYXN1x_4HchCMg3ujcfLwD7WzfO7G2uM9s/edit#

2022-08-09 15:53 UTC, WilcoFiers requested changes
Can you fix the typo in the minimum bounding box definition too? "(such **has** hypertext links)" should be "(such **as** hypertext links)"

2022-08-15 20:02 UTC, patrickhlauke commented on guidelines/sc/22/focus-appearance.html
> +    <p class="note">The position, size, and shape of user interface components and sub-components is determined by its visual presentation. The visual presentation includes, but is not limited to the
this sets out to initially define the position/size/shape of the UIC. but this seems to come out of the blue, as nothing up to this point talked about any of those things. perhaps it needs a slightly different intro ... something more like "What is perceived as the user interface component and any sub-components (to determine whether or not a focus indicator actually encloses it) depends on its visual presentation." or similar? Basically, need to somehow glue to together so it's clear this tries to explain what needs to be taken into consideration when determining what the focus indicator actually needs to *enclose*?

2022-08-30 14:46 UTC, mbgower commented
Thanks for the tweaks that removed "is not limited to" and "size".
You may want to think about saying "area" instead of "size" in the other usage, resulting in it being "...(to determine enclosure or area..." . Otherwise, looks good

2022-09-04 11:02 UTC, alastc commented
Closing as we merged a different branch that covered the same things.

2022-09-04 11:02 UTC, closed without merging