Update consistent-help.html
w3c/wcag pull request #2919
Opened 2023-01-13 15:30 UTC by bruce-usab

Per backlog call 1-6-23 

Closes #2413

2023-01-14 13:40 UTC, patrickhlauke requested changes

2023-01-14 13:40 UTC, patrickhlauke commented on understanding/22/consistent-help.html
> +         <li>Enabling users (especially those with cognitive disabilities) to find solutions while expressing their question using their own words (for example by interacting with a <q>chatbot</a>) i
`<q>chatbot</a>` probably needs to be `<q>chatbot</q>` (unless you're linking to a defined term, in which case change the opening tag to `<a>`)

2023-01-15 18:43 UTC, patrickhlauke approved these changes

2023-01-31 13:22 UTC, detlevhfischer approved these changes

2023-01-31 17:49 UTC, merged