Remove technique H59
w3c/wcag pull request #2970
Opened 2023-01-26 19:00 UTC by patrickhlauke

the technique is out of date and has no real-world usefulness, since no major browser these days has any kind of `<link rel="...">` navigation toolbar.

Closes #1234

2023-06-29 13:47 UTC, patrickhlauke commented
@alastc @mbgower any chance this could be looked at? it's fairly non-controversial in my view, because...no browser has any meaningful support for these `<link rel="..." ...>` constructs these days (and even back in the old days, only Opera really did something with them, for other browsers you needed extensions)

2023-12-01 16:44 UTC, dbjorge requested changes

2023-12-01 16:44 UTC, dbjorge commented on wcag20/sources/misc/wcag2.json
> -                  "id": "TECH:G127",
This looks off to me - G127 is still a sufficient technique for 2.4.8, no?

2023-12-02 14:48 UTC, dbjorge approved these changes

2023-12-15 16:55 UTC, ljoakley commented
Refers to the use of the rel attribute using next/previous in a link tag. Google removed support for next/previous/ in 2019. 77% of all web traffic as of November 2023 uses google, advise marking it as deprecated as rel has many other uses besides next/previous.

2023-12-15 18:08 UTC, ljoakley approved these changes

2024-01-26 15:10 UTC, bruce-usab commented
On deck for call 1/26, no objections to deleting so far...

2024-02-13 18:08 UTC, merged