Update H71.html
w3c/wcag pull request #3096
Opened 2023-03-08 12:09 UTC by detlevhfischer

Modify test section to include the requirement that legent is first child in fieldset 

Closes  #3090

2023-03-08 12:13 UTC, dd8 approved these changes
Looks good to me

2024-05-29 03:37 UTC, fstrr requested changes
Could you wrap the `fieldset` in "is the first child in the fieldset" in a `<code class="language-html">` element please? Then it's good to go.

2024-05-29 03:41 UTC, fstrr commented
Also: wow, I didn't realise this was assigned to me. Sorry for taking over a year to see it.

2024-05-29 07:39 UTC, patrickhlauke commented on techniques/html/H71.html
> +            <li>Check that each <code class="language-html">fieldset</code> has a <code class="language-html">legend</code> element that is the first child in the fieldset and includes a description
```suggestion
            <li>Check that each <code class="language-html">fieldset</code> has a <code class="language-html">legend</code> element that is the first child in the <code class="language-html">fieldset</code> and includes a description for that group.</li>
```

2024-06-21 14:32 UTC, patrickhlauke approved these changes

2024-07-10 22:17 UTC, merged