Update identify-input-purpose.html
w3c/wcag pull request #3310
Opened 2023-07-28 14:16 UTC by mbgower

Replaced relative link with FQDN link https://www.w3.org/TR/WCAG21/#input-purposes since the existing one is triggering nothing.

2023-07-31 13:59 UTC, scottaohara commented
this is related to the larger issue of the [understanding docs losing their link back to the spec](https://github.com/w3c/wcag/issues/3289) - and that [all links back to the spec from understanding docs are broken](https://github.com/w3c/wcag/issues/3288) - as this PR further identifies.

fixing these should obviously be done, but is a one off PR the way to go, or is there a way to fix all of these broken links at once?

2023-07-31 15:49 UTC, alastc commented
I think this is a separate thing. There is an the include for SCs that is pulled into both the Spec and the understanding docs.

For definitions, the relative link works because they are also on both. However, this is to an appendix, the build-template doesn't account for that.

So I think a hard-coded link is the way to go, but we'll need to do different ones for WCAG 2.1 and 2.2.

2023-07-31 16:38 UTC, scottaohara commented
i understand your take on this @alastc, i was coming from the mindset that in other specs like HTML AAM a generic URL can be used in the source and through the build process of the spec, the necessary URLs can be populated in.  So, if that's not a feature that can be used over here, then yes.  agreed.  a separate issue than the primary issue that i linked to.  But, i did intend to be calling out these broken links, as well, in the original issue i filed,

2024-05-27 07:26 UTC, TLC82 requested changes
Delete

2024-10-18 22:12 UTC, kfranqueiro commented
The Eleventy-based build system handles this case correctly for 2.2 now, and will eventually also be used to rebuild 2.1 docs (see #4007). This change should not be necessary (and we should avoid hard-coding links to specific versions of the spec), so I'll close this.

2024-10-18 22:12 UTC, closed without merging