Consolidation on the usage of website.
w3c/wcag pull request #3662
Opened 2024-01-29 15:12 UTC by HaTheo

2024-01-29 15:29 UTC, patrickhlauke requested changes
I think we want/need to exclude all material inside the `wcag20` folder in this PR

2024-01-29 15:31 UTC, HaTheo commented
> I think we want/need to exclude all material inside the `wcag20` folder in this PR

Yes, I was wondering about this. I would be happy to exclude previous versions of WCAG.

2024-01-29 16:14 UTC, patrickhlauke approved these changes

2024-01-29 16:15 UTC, patrickhlauke commented
Thanks for the changes Theo, think this is looking good now

2024-01-29 17:43 UTC, fstrr commented
As a sidenote to this, I notice [ARIA](https://github.com/w3c/aria?tab=readme-ov-file#role-of-editors) links to a now non-existent [W3C Manual Of Style](http://www.w3.org/2001/06/manual/).

I'd sort of be interested in reviving that.

2024-01-29 18:18 UTC, fstrr commented
As a sidenote, we talked about a [W3C Manual Of Style](https://www.w3.org/Guide/manual-of-style/) last Friday, and I think we said it wasn't a thing anymore. It looks like it does and was updated this month.

2024-11-29 15:46 UTC, patrickhlauke commented
Due to the high number of merge conflicts, suggest this (if we want to go ahead with it) be redone fresh

2024-11-29 16:40 UTC, alastc commented
Dicsssion from TF: We need to re-do this one, partly due to clashes, but partly due to the normative ones already being done. We need to keep the normative doc changes separate from the informative docs (understanding/techniques).

2024-12-06 16:41 UTC, mbgower commented
@mbgower will make a new PR replciating his normative style changes to the non-normative documents.

2025-02-21 23:16 UTC, bruce-usab commented
Discussed on backlog call 2/21.  @mbgower volunteered to do the cleanup and separate out the corrections on TR docs from the WAI docs.

2025-02-24 23:42 UTC, mbgower commented
I have created https://github.com/w3c/wcag/pull/4242 to replace this.

2025-02-28 15:34 UTC, patrickhlauke commented
Should this be closed if it's superseded by #4242 ?

2025-02-28 16:12 UTC, mbgower commented
Closed as resolved by https://github.com/w3c/wcag/pull/4242

2025-02-28 16:12 UTC, closed without merging