Fix to correct url
w3c/wcag pull request #3697
Opened 2024-02-17 02:05 UTC by ryo-manba

2024-02-17 09:07 UTC, rscano approved these changes

2024-04-05 15:18 UTC, patrickhlauke requested changes
I'd suggest making this more robust/future-proof by using relative, rather than absolute, URLs

2024-04-06 09:30 UTC, patrickhlauke approved these changes

2024-04-12 14:45 UTC, bruce-usab approved these changes
Thank you @ryo-manba  and @patrickhlauke

2024-04-12 18:43 UTC, bruce-usab commented
Discussed 4/12 and Ready for approval.

2024-05-14 17:51 UTC, closed without merging