Change <br> to <br/>
w3c/wcag pull request #3879
Opened 2024-05-24 17:46 UTC by patrickhlauke

Due to the XML-based publication pipeline, need to have self-closing `<br/>`. Otherwise when trying to build locally at least, `ant` chokes.

2024-05-24 18:40 UTC, scottaohara approved these changes
took a look and approving per the rational as to why this needs to happen.  but otherwise, boo :)

2024-06-07 14:38 UTC, bruce-usab requested changes
Should Understanding Target Size Enhanced uses something semantic rather than BR ?

2024-06-07 14:59 UTC, fstrr commented
Seems like a prima candidate for a description list.

2024-06-07 15:10 UTC, patrickhlauke commented
can/should we do that in a separate PR, rather than this very targeted (pun) PR to just fix some xml?

2024-06-07 15:39 UTC, bruce-usab approved these changes

2024-06-07 15:40 UTC, bruce-usab commented
From call 6/7, concur with just making this bug fix.

2024-06-07 15:48 UTC, fstrr commented
'Tis done - #3901

2024-06-07 16:04 UTC, patrickhlauke commented
as @iadawn 's https://github.com/w3c/wcag/pull/3899 already fixes the first change for the target size understanding (likely he bumped into the same issue i saw when trying to build the spec/understanding), and the other instances of naked `<br>` do *not* need to be fixed as they don't go through the XML pipeline...closing this as superseded

2024-06-07 16:04 UTC, closed without merging