Update labels-or-instructions.html
w3c/wcag pull request #3888
Opened 2024-05-31 16:12 UTC by scottaohara

closes #3887

clarifies that wcag is not recommending use of placeholder text, and instead recommends accompanying text to provide the information (which could then be part of label or description - but those details are not applicable to this SC so not specified in the update)

This helps better match [technique g89](https://www.w3.org/WAI/WCAG22/Techniques/general/G89.html) which includes the date format expectation as part of the label text

2024-05-31 16:39 UTC, patrickhlauke requested changes

2024-05-31 16:39 UTC, patrickhlauke commented on understanding/20/labels-or-instructions.html
> +         <li>A field for entering a date is provided text instructions to indicate the correct format
```suggestion
         <li>A field for entering a date has text instructions to indicate the correct format
```
cleaner/simpler

2024-06-07 15:59 UTC, patrickhlauke approved these changes

2024-06-07 21:11 UTC, bruce-usab approved these changes

2024-07-10 22:19 UTC, merged