Fix typo
w3c/wcag pull request #3938
Opened 2024-07-01 13:08 UTC by daniel-montalvo

Fixes #3937

2024-07-01 14:30 UTC, scottaohara approved these changes

2024-07-05 19:07 UTC, patrickhlauke requested changes

2024-07-05 19:07 UTC, patrickhlauke commented on techniques/failures/F26.html
> -      <li><a href="../aria/ARIA24">ARIA24</a></li>
this change seems unrelated?

2024-07-08 09:38 UTC, daniel-montalvo commented on techniques/failures/F26.html
> -      <li><a href="../aria/ARIA24">ARIA24</a></li>
Should be fixed now

2024-07-08 10:04 UTC, patrickhlauke approved these changes

2024-07-22 09:53 UTC, giacomo-petri approved these changes

2024-11-19 18:04 UTC, merged