Tweak the concept of "draw" in 2.5.8 for the spacing checks
w3c/wcag pull request #4057
Opened 2024-09-07 09:35 UTC by patrickhlauke

Closes https://github.com/w3c/wcag/issues/3895

2024-09-13 14:52 UTC, bruce-usab requested changes
I like all the edits except first one, "possible" to "theoretically possible".

Maybe "conceptually possible" or leave as-is?  With the other edits, I do not think "draw" will be taken as a concrete literal requirement.

2024-09-13 15:34 UTC, patrickhlauke commented on understanding/22/target-size-minimum.html
> +            <p>When a target is smaller than 24 by 24 CSS pixels, it is <em>undersized</em>. In this case, we check if it at least has sufficient <em>spacing</em> by drawwing an imaginary 24 CSS pixe
```suggestion
            <p>When a target is smaller than 24 by 24 CSS pixels, it is <em>undersized</em>. In this case, we check if it at least has sufficient <em>spacing</em> by drawing an imaginary 24 CSS pixel diameter circle over the undersized target, centered on the target's <a>bounding box</a>. For rectangular targets, the bounding box coincides with the target itself – thus, the circle is placed on the center of the target. If the target is <em>not</em> rectangular – for instance, if the target is clipped, has rounded corners, or if it's a more complex clickable SVG shape – we need to first determine the bounding box, and then find the box's center. Note that for concave shapes, the center of the bounding box may be outside of the target itself. Now, we center the circle on the center of the bounding box.</p>
```

2024-09-13 15:44 UTC, bruce-usab commented
Discussed 9/13, minor change on call.  Move to Ready for approval.

2024-09-13 15:44 UTC, patrickhlauke commented on understanding/22/target-size-minimum.html
> +            <p>For a target to be "at least 24 by 24 CSS pixels", it must be theoretically possible to draw a solid 24 by 24 CSS pixel square, aligned to the horizontal and vertical axis such that th
```suggestion
            <p>For a target to be "at least 24 by 24 CSS pixels", it must be conceptually possible to draw a solid 24 by 24 CSS pixel square, aligned to the horizontal and vertical axis such that the square is completely within the target (does not extend outside the target's area).</p>
```

2024-09-13 21:44 UTC, bruce-usab approved these changes

2024-11-21 00:38 UTC, mbgower commented
This was date-stamped as being sent for WG approval on oct 10. I have left that stamp in place, but noting here that it was sent as part of the Nov 20 changes to the working group.

2024-12-13 22:42 UTC, merged