Cfc web pages
w3c/wcag pull request #4080
Opened 2024-09-20 16:47 UTC by mbgower

Ensures all occurrences of "web page" are two words and lower case.

One of a number of style changes to the guidelines that I accidentally commited to main, and then turned into separate branches.

2024-09-20 16:49 UTC, mbgower commented on guidelines/sc/20/three-flashes-or-below-threshold.html
> +   <p><a>web pages</a> do not contain anything that flashes more than three times in any one second period,
```suggestion
   <p><a>Web pages</a> do not contain anything that flashes more than three times in any one second period,
```

2024-09-20 17:14 UTC, mbgower commented
@shawna-slh if you have time to eyeball this and confirm I haven't unintentionally altered something that should remain capitalized (i.e., the start of a sentence), I would welcome.

2024-09-23 21:18 UTC, bruce-usab requested changes
@mbgower I found a few case typos.

2024-09-23 21:18 UTC, bruce-usab commented on guidelines/index.html
> +						<p><strong>success criteria</strong> - For each guideline, testable success criteria are provided to allow WCAG 2.2 to be used where requirements and conformance testing are necessary such as i
Success criteria should use title case since paragraph does that:  
> Sufficient and Advisory Techniques

2024-09-23 21:18 UTC, bruce-usab commented on guidelines/index.html
> +                <p>Success criteria within this specification which the Working Group has identified possible implications for privacy, either by providing protections for end users or which are impo
>...other Success criteria

I am not sure if both words should be capitalized, but one of the two is wrong.

2024-09-23 21:18 UTC, bruce-usab commented on guidelines/index.html
>                  <h2>Security Considerations</h2>
Same as previous comment, `other Success criteria`

2024-09-27 14:59 UTC, bruce-usab approved these changes
Approve after we double check line 56 of index.html on call.

2024-09-27 15:25 UTC, mbgower commented on guidelines/index.html
> +						<p><strong>success criteria</strong> - For each guideline, testable success criteria are provided to allow WCAG 2.2 to be used where requirements and conformance testing are necessary such as i
```suggestion
						<p><strong>Success criteria</strong> - For each guideline, testable success criteria are provided to allow WCAG 2.2 to be used where requirements and conformance testing are necessary such as in design specification, purchasing, regulation, and contractual agreements. In order to meet the needs of different groups and different situations, three levels of conformance are defined: A (lowest), AA, and AAA (highest). Additional information on WCAG levels can be found in <a href="https://www.w3.org/WAI/WCAG22/Understanding/conformance#levels">Understanding Levels of Conformance</a>.</p>
```

2024-09-27 15:27 UTC, mbgower commented on guidelines/index.html
>  						<p><strong>Sufficient and Advisory Techniques</strong> - For each of the <em>guidelines</em> and <em>success criteria</em> in the WCAG 2.2 document itself, the working group has also documented
```suggestion
						<p><strong>Sufficient and advisory techniques</strong> - For each of the <em>guidelines</em> and <em>success criteria</em> in the WCAG 2.2 document itself, the working group has also documented a wide variety of <em>techniques</em>. The techniques are informative and fall into two categories: those that are <em>sufficient</em> for meeting the success criteria and those that are <em>advisory</em>. The advisory techniques go beyond what is required by the individual success criteria and allow authors to better address the guidelines. Some advisory techniques address accessibility barriers that are not covered by the testable success criteria. Where common failures are known, these are also documented. See also <a href="https://www.w3.org/WAI/WCAG22/Understanding/understanding-techniques">Sufficient and Advisory Techniques in Understanding WCAG 2.2</a>.</p>
```

2024-09-27 15:29 UTC, mbgower commented on guidelines/index.html
>  						<p><strong>Sufficient and Advisory Techniques</strong> - For each of the <em>guidelines</em> and <em>success criteria</em> in the WCAG 2.2 document itself, the working group has also documented
@shawna-slh what's your feeling on these?

2024-09-27 15:30 UTC, scottaohara approved these changes
lgtm outside of the question about title casing the list items - i'm personally fine with whatever the resolution to that ends up being.

2024-09-27 16:51 UTC, bruce-usab commented
Discussed on TF call, with consensus on changes.  @mbgower is going to check with @shawna-slh on use of title case with [Layers of Guidance](https://www.w3.org/TR/WCAG22/#wcag-2-layers-of-guidance) section.

2024-10-04 17:14 UTC, bruce-usab approved these changes

2024-10-04 17:17 UTC, bruce-usab commented
Discussed on backlog call 10/4, reverting to keeping title case for first word(s) following bullets of Layers of Guidance.

2024-11-19 16:06 UTC, merged